### ISSUE TITLE
[MedtrumKit] "Failed to find device"

### ISSUE THREAD

**Issue by LiroyvH** [nightscout/Trio#759]
## Describe the bug
When deleting a pump base and then adding one with another serial number, when attempting to connect/start prime afterwards: the app keeps saying "Error: failed to find device". I tried deleting and adding it again and quadruple checked the serial number (even attempted copy/paste from a picture): same error, over and over. I then force killed the app, started the app again and went back to the pump menu. It remembered the serial number. This time when I tapped the button: it immediately connected and started priming - connection obviously successful. 

## Attach a Log
Logs available on request. 

## To Reproduce
*Steps to reproduce the behavior:*
1. Delete Medtrum pump
2. Add new Medtrum pump (diff serial)
3. Attempt to start prime
4. ???
5. Profit

## Expected behavior
I expected the pump to connect without having to restart Trio.

## Screenshots
None taken. 

### Smartphone:
16 Pro with 18.6.2. 

### Pump:
Medtrum Nano 200U

### CGM:
G6, official app

### Trio Version:
Medtrum feature branch (fully synced) with manual submodule re-sync as advised by @bastiaanv. 

## Technical Details
Already provided. 

## Additional context
Nah.

**Comment by bastiaanv** [comment]
@LiroyvH I suppose you do not have the Medtrum logs of this issue? :)

**Comment by LiroyvH** [comment]
@bastiaanv I've captured the logs for sure, I'll send them over to you. :)

**Comment by Lamercho** [comment]
Same happened to me after switching from 300iu base to 200iu. Even after force close it didn't connect right away but I kept trying and after maybe 5 mins was able to add it.

**Comment by bastiaanv** [comment]
@Lamercho @LiroyvH 
This issue should be fixed in SHA [b5a3477](https://github.com/loopandlearn/MedtrumKit/commit/b5a3477cc9becd8e1c92f3217d5f138495285db9).

If one of you are will to test, that would be great!

**Comment by Lamercho** [comment]
Strike that, I wasnt on latest dev branch of MedtrumKit - totally my fault. When I have some new patches will test again.

**Comment by bastiaanv** [comment]
The fix for this is merged in #766, closing the issue.

If this is not resolved, feel free to re-open the PR :)

**Comment by LiroyvH** [comment]
I think this isn't resolved yet. Yesterday I switched pumpbase. Changing the serial without removing pump lead to a host of errors, almost seemed like it tried to send command to start priming to old base (which was still powered on, could be something needs handling there due to identical bluetooth naming? But one bug a time.). Restart 1 didn't fix. Removing pump and restarting Trio and adding new pump looks like it succeeded after 2 or 3 attempts. 

Logs uploaded for analysis. Might be the issue in this scenario (multi base available) needs additional explanation rather than a software fix. But again, I'm just throwing out ideas here. Maybe it *is* software, heh.

**Comment by LiroyvH** [comment]
Ok, so today I received new pumpbases of which I started using one.

Issue:
- Delete pump, confirm deleted; Trio shows "Add pump" logo on main screen
- Then stay idle for a while whilst filling patch 'n all that; find Trio dead in background as tapping it shows the "getting things ready for you" routine
- Upon relaunching Trio: find out pump is back again and not actually deleted, see "Insulin suspended!!" in red on main screen instead of "add pump" logo that it was showing before. Upon tapping that: turns out it remembered serial number of the (deleted) pumpbase as well.
- Delete it again. Then tap add pump, enter serial number of new pumpbase.
- Start prime. Error: failed to find device, cannot connect. Try again and again, no joy.
- Kill Trio
- Start Trio again, open pump: it remembered the new serial number (yay)
- Tap "start prime" again. Now it does start to prime.

If logs are needed, I can upload them. Captured right after it started connecting again. (I captured Trio logs as well as Medtrum patch logs.) However, I'm not sure if the patch logs are expunged when deleting pump... That'd pose an issue as I'd have to save the logs in between the multiple attempts to to get this going. If that's needed, I can do that on next patch change. 

Just to note this is not a major issue, just annoying and it of course shouldn't be so difficult to change pumpbase.

**Comment by bastiaanv** [comment]
I am analyzing the Medtrum logs and I see the following:
- Patch gets deactivated
- Some small errors, because Trio is trying to sync the pump data but the patch is deactivated (this is good)
  - During this time, the CBManagerState switches from poweredOn to unsupported
- MedtrumKit detects a change in SN and clears all references to the old patch
- ble scanning fails, because CBManagerState is unsupported

It is not clear (yet), why the CBManagerState switches to unsupported.
It is not an issue related to permissions nor to ble being turned off, since the docs suggests other states for that:
https://developer.apple.com/documentation/corebluetooth/cbmanagerstate

Restarting Trio seems to fix this issue. Maybe re-initializing CBCentralManager could fix it, but I am not sure about that.

For now, I could improve the error message, but I am not sure if a fix is possible...

**Comment by LiroyvH** [comment]
@bastiaanv Could the switch to "unsupported" be because I deleted the pump? (Though I'm still unsure why after deleting the pump, it comes back with all settings retained after restarting Trio (either on purpose or because Trio got shot in the back by iOS :P). Just referencing that behaviour in case somehow it adds two pumps and triggers issues? (Long shot, just throwing ideas out there.))

-edit-
You note "MedtrumKit detects a change in SN and clears all references to the old patch". Just to be sure pointing out that's odd as well, as I deleted the pump prior to adding the new pumpbase with different serial number. Shouldn't it have cleared it already? This might be a seperate "issue" though. Sorry if I'm creating noise/distraction. Just ensuring all behaviour/potential causes are noted. :)

**Comment by bastiaanv** [comment]
Go thing to point out the deleting again. I will look into that!

About the edit, detecting a change might also be from nothing (because the pumpManager is deleted) to something.
So not really an issue :)

**Comment by LiroyvH** [comment]
@bastiaanv So this time around, I've changed to another pumpbase *without* first deleting the pump. Now, it worked instantly and did not throw any of the usual errors and did not require a restart of Trio. New logs have been uploaded now  to the same folder (in the new subfolder), in case they're useful. 

-edit- Unfortunately Trio did get stuck in "Looping" during failure/patch change, and with no way to make it stop/restart looping I ended up killing and restarting Trio anyway - lol. If I need to report that as a separate issue, please let me know. (It should bail out of an attempted loop after a while imho)

**Comment by bastiaanv** [comment]
Is this still a relevant issue?

**Comment by LiroyvH** [comment]
> Is this still a relevant issue?

Yes I believe so. 
There's two ways to go about changing a pumpbase:

1.) Remove the Medtrum altogether, then add new pump and type in the new serial number

2.) Deactivate the patch, then you're brought back to the screen where the pumpbase serial number is shown. Just change that to the serial number of your "new" pumpbase and proceed. 

In scenario 1: all kind of weird thing start happening, it doesn't truly seem to remove the pump (at first try) and changing does not go smoothly. You'll get "failed to find device" warnings constantly until you kill Trio, restart it. (You may have to do so twice) Typically, when you do this: you may find the old pumpbase suddenly being back after restarting Trio, even though you had deleted it and even though Trio showed the "add pump" icon on home. 

In scenario 2: this issue does not occur at all. I've been doing it this way for a few weeks now and changing has gone very smoothly. Not a single "failed to find device" error, it just starts priming as expected. 

However, its a.) not super obvious you can actually change the serial number this way, b.) I think it would be best to fix the bug. 

If you need more logs (from before/after a specific user action or following specific steps) - please let me know, I can force the issue as its very easily reproducible; though only during a patch change as otherwise I'll ruin the patch. :P
